### PR TITLE
Escaped {{ in MD used for generating pages

### PR DESCRIPTION
**Pull request by hanak**
Closes https://github.com/React-Automation-Studio/React-Automation-Studio/issues/62

**Problem***

Deployment of GitHub pages is failing due to treating {{ in source code as a tag.

**Solution**

    This update uses {% raw %} in order to turn off the interpretation of {{.
    This update corrects a tags at a table.
    This update corrects location of images LoadSave.md.

**Test**

This is a documentation formatting update only. No functional code change. Result has been verifies using github earlier.

### CODE REVIEW

**Comment by hanak** [comment]
This is a re-merge of changes reverted through #69. Please, review.

**Comment by hanak** [comment]
I have re-run generation of the pages using the branch 62-test (see https://github.com/React-Automation-Studio/React-Automation-Studio/tree/62-test). The workflow "pages build and deployment / deploy (dynamic)" was successful.

**Comment by wduckitt** [comment]
Hi, I dont think we can merge this solution, it creates {%raw%} prints in the styleguide.

See the attached screenshot: 
image

**Comment by wduckitt** [comment]
I had a look through previous emails. In the past for previous pushes to the master, Github   page build complained only about ReactApp/src/components/AlarmHandler/AlarmHandler.md
The markdown files modified by this PR are only used to build the styleguide pages, they are not intended as readme's in github pages. Perhaps, lets only try to adress the one that causes the pagebuild error message and leave the the othe 61 md files in the original manner?

**Comment by hanak** [comment]
Unfortunately, I thought it is AlarmHandle.md only too. Yet, as I masked "{{", it turned out every .MD file which contains "{{" is reported as a problem because the processing system treats "{{" as an opening tag to a variable. So, I updated all files reported with `{% raw %}`. Hence, so many files files were affected. Sadly, this impacts the styleguide as you have mentioned which makes this solution useless. If the pages are meant to consists of Readme.md only, I can try to see whether there is a configuration input which will limit the processor/publisher to Readme.md instead of searching for all .MD files it finds. Assuming such a configuration is possible, would limiting the github pages to Readme.md work (as a solution)?

**Comment by hanak** [comment]
Since masking {{ colliders with intended use of the MD files, I will try to address this issue through configuration. As a consequence, this pull request should be closed as obsolete.

**Pull request closed without merging**
