### PR TITLE
Clean pyMongoUtils.py

### LINKED ISSUE #52: pyMongoUtils: Remove unused code and empty lines and update to follow PEP
* Follow guidelines of #34 on `utils/python/mongoDb/pyMongoUtils.py`
* Add `pyMongoUtils.py` to the check introduced through #45.

### PR DESCRIPTION
**Pull request by giosava94**
This PR resolves #52. The last commit changes the function name from camelCase to snake_case and automatically update all files using that function (it can be reverted if needed).

### CODE REVIEW

**Comment by hanak** [comment]
I think it looks good. I have just merged the pull request which adds the formatting check to the master branch. Would it be possible to extend the formatting check with `pyMongoUtils.py`, please?

**Comment by giosava94** [comment]
Since in #38 we will have to move all python files in the same folder, can I move this file in pvServer folder? This way I have to change nothing in the github action and we are a step forward in the roadmap. Does this sound good for you?

**Comment by hanak** [comment]
Good idea. Let's do it.

**Review by hanak — APPROVED** [review]
Nice work. Approved.

**Pull request merged**
