### PR TITLE
Update readme links

### PR DESCRIPTION
**Pull request by wduckitt**
The main README.md file has been updated with new repository links.

The docker install instructions and links have also been updated

### CODE REVIEW

**Review by hanak — COMMENTED** [review]
I think the pull request missed a link on the lines 155 and 484. Just try to search for "wdickitt" in the README.

**Comment by hanak** [comment]
Also, I have noticed old links in:
* ReactApp/src/docs/introduction.md
* ReactApp/src/docs/installation/installation.md

And, in:
* ReactApp/src/components/ArchiverDataViewer/AchiverDataViewer.js
* ReactApp/src/components/ArchiverDataViewer/AchiverDataViewerDemo.js

Would it be possible to correct the links or create corresponding issue, please?

**Comment by wduckitt** [comment]
Ok I think thats all the links updated

**Review by hanak — APPROVED** [review]
Changes look good. Approved.

**Pull request merged**
